fix(): travis

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,13 +1,34 @@
 #!/bin/bash
+safeRunCommand() {
+  typeset cmnd="$*"
+  typeset ret_code
 
-# run local truffle node
-ganache-cli &
-GANACHE=$!
+  echo cmnd=$cmnd
+  eval $cmnd
+
+  ret_code=$?
+  if [ $ret_code != 0 ]; then
+    printf "Error : [%d] when executing command: '$cmndE'" $ret_code
+    exit $ret_code
+  fi
+}
+
+# ara node_modules/.bin to PATH
+PATH=$(npm bin):$PATH
+
+# installation
+npm install -g ganache-cli truffle
+
+# run local ganache node
+ganache-cli -l 0x7A1200 &
 sleep 5
 
-truffle migrate --network local
+command="truffle migrate --reset --network local"
+safeRunCommand "$command"
 
-ava test --verbose
+# ava tests
+command="ava test --verbose"
+safeRunCommand "$command"
 
 # cleanup
-kill $GANACHE
+pkill -f ganache 
